import { lazy } from 'react'
import type { AppDefinition } from '@/types'

// Lazy load all apps
export const appRegistry: Record<string, AppDefinition> = {
  settings: {
    id: 'settings',
    name: 'Settings',
    icon: 'settings',
    component: lazy(() => import('./settings')),
    backgroundColor: '#8E8E93',
    statusBarStyle: 'light',
  },
  calculator: {
    id: 'calculator',
    name: 'Calculator',
    icon: 'calculator',
    component: lazy(() => import('./calculator')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  clock: {
    id: 'clock',
    name: 'Clock',
    icon: 'clock',
    component: lazy(() => import('./clock')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  notes: {
    id: 'notes',
    name: 'Notes',
    icon: 'notes',
    component: lazy(() => import('./notes')),
    backgroundColor: '#FFCC00',
    statusBarStyle: 'dark',
  },
  photos: {
    id: 'photos',
    name: 'Photos',
    icon: 'photos',
    component: lazy(() => import('./photos')),
    backgroundColor: '#FFFFFF',
    statusBarStyle: 'dark',
  },
  safari: {
    id: 'safari',
    name: 'Safari',
    icon: 'safari',
    component: lazy(() => import('./safari')),
    backgroundColor: '#FFFFFF',
    statusBarStyle: 'dark',
  },
  messages: {
    id: 'messages',
    name: 'Messages',
    icon: 'messages',
    component: lazy(() => import('./messages')),
    backgroundColor: '#34C759',
    statusBarStyle: 'light',
  },
  phone: {
    id: 'phone',
    name: 'Phone',
    icon: 'phone',
    component: lazy(() => import('./phone')),
    backgroundColor: '#34C759',
    statusBarStyle: 'light',
  },
  camera: {
    id: 'camera',
    name: 'Camera',
    icon: 'camera',
    component: lazy(() => import('./camera')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  weather: {
    id: 'weather',
    name: 'Weather',
    icon: 'weather',
    component: lazy(() => import('./weather')),
    backgroundColor: '#5AC8FA',
    statusBarStyle: 'light',
  },
  calendar: {
    id: 'calendar',
    name: 'Calendar',
    icon: 'calendar',
    component: lazy(() => import('./calendar')),
    backgroundColor: '#FF3B30',
    statusBarStyle: 'light',
  },
  maps: {
    id: 'maps',
    name: 'Maps',
    icon: 'maps',
    component: lazy(() => import('./maps')),
    backgroundColor: '#34C759',
    statusBarStyle: 'light',
  },
}
