import { lazy } from 'react'
import type { AppDefinition } from '@/types'

// Lazy load all apps
export const appRegistry: Record<string, AppDefinition> = {
  settings: {
    id: 'settings',
    name: 'Settings',
    icon: 'settings',
    component: lazy(() => import('./settings')),
    backgroundColor: '#8E8E93',
    statusBarStyle: 'light',
  },
  calculator: {
    id: 'calculator',
    name: 'Calculator',
    icon: 'calculator',
    component: lazy(() => import('./calculator')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  clock: {
    id: 'clock',
    name: 'Clock',
    icon: 'clock',
    component: lazy(() => import('./clock')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  notes: {
    id: 'notes',
    name: 'Notes',
    icon: 'notes',
    component: lazy(() => import('./notes')),
    backgroundColor: '#FFCC00',
    statusBarStyle: 'dark',
  },
  photos: {
    id: 'photos',
    name: 'Photos',
    icon: 'photos',
    component: lazy(() => import('./photos')),
    backgroundColor: '#FFFFFF',
    statusBarStyle: 'dark',
  },
  safari: {
    id: 'safari',
    name: 'Safari',
    icon: 'safari',
    component: lazy(() => import('./safari')),
    backgroundColor: '#FFFFFF',
    statusBarStyle: 'dark',
  },
  messages: {
    id: 'messages',
    name: 'Messages',
    icon: 'messages',
    component: lazy(() => import('./messages')),
    backgroundColor: '#34C759',
    statusBarStyle: 'light',
  },
  phone: {
    id: 'phone',
    name: 'Phone',
    icon: 'phone',
    component: lazy(() => import('./phone')),
    backgroundColor: '#34C759',
    statusBarStyle: 'light',
  },
  camera: {
    id: 'camera',
    name: 'Camera',
    icon: 'camera',
    component: lazy(() => import('./camera')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  weather: {
    id: 'weather',
    name: 'Weather',
    icon: 'weather',
    component: lazy(() => import('./weather')),
    backgroundColor: '#5AC8FA',
    statusBarStyle: 'light',
  },
  calendar: {
    id: 'calendar',
    name: 'Calendar',
    icon: 'calendar',
    component: lazy(() => import('./calendar')),
    backgroundColor: '#FF3B30',
    statusBarStyle: 'light',
  },
  maps: {
    id: 'maps',
    name: 'Maps',
    icon: 'maps',
    component: lazy(() => import('./maps')),
    backgroundColor: '#34C759',
    statusBarStyle: 'light',
  },
  reminders: {
    id: 'reminders',
    name: 'Reminders',
    icon: 'reminders',
    component: lazy(() => import('./reminders')),
    backgroundColor: '#FF9500',
    statusBarStyle: 'light',
  },
  news: {
    id: 'news',
    name: 'News',
    icon: 'news',
    component: lazy(() => import('./news')),
    backgroundColor: '#FC3158',
    statusBarStyle: 'light',
  },
  health: {
    id: 'health',
    name: 'Health',
    icon: 'health',
    component: lazy(() => import('./health')),
    backgroundColor: '#FF2D55',
    statusBarStyle: 'light',
  },
  wallet: {
    id: 'wallet',
    name: 'Wallet',
    icon: 'wallet',
    component: lazy(() => import('./wallet')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  music: {
    id: 'music',
    name: 'Music',
    icon: 'music',
    component: lazy(() => import('./music')),
    backgroundColor: '#FC3C44',
    statusBarStyle: 'light',
  },
  podcasts: {
    id: 'podcasts',
    name: 'Podcasts',
    icon: 'podcasts',
    component: lazy(() => import('./podcasts')),
    backgroundColor: '#8F5AC5',
    statusBarStyle: 'light',
  },
  tv: {
    id: 'tv',
    name: 'TV',
    icon: 'tv',
    component: lazy(() => import('./tv')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  books: {
    id: 'books',
    name: 'Books',
    icon: 'books',
    component: lazy(() => import('./books')),
    backgroundColor: '#FF9500',
    statusBarStyle: 'light',
  },
  appstore: {
    id: 'appstore',
    name: 'App Store',
    icon: 'appstore',
    component: lazy(() => import('./appstore')),
    backgroundColor: '#007AFF',
    statusBarStyle: 'light',
  },
  fitness: {
    id: 'fitness',
    name: 'Fitness',
    icon: 'fitness',
    component: lazy(() => import('./fitness')),
    backgroundColor: '#A2D729',
    statusBarStyle: 'light',
  },
  translate: {
    id: 'translate',
    name: 'Translate',
    icon: 'translate',
    component: lazy(() => import('./translate')),
    backgroundColor: '#007AFF',
    statusBarStyle: 'light',
  },
  compass: {
    id: 'compass',
    name: 'Compass',
    icon: 'compass',
    component: lazy(() => import('./compass')),
    backgroundColor: '#000000',
    statusBarStyle: 'light',
  },
  shortcuts: {
    id: 'shortcuts',
    name: 'Shortcuts',
    icon: 'shortcuts',
    component: lazy(() => import('./shortcuts')),
    backgroundColor: '#FF2D55',
    statusBarStyle: 'light',
  },
  'voice-memos': {
    id: 'voice-memos',
    name: 'Voice Memos',
    icon: 'voice-memos',
    component: lazy(() => import('./voice-memos')),
    backgroundColor: '#EF4136',
    statusBarStyle: 'light',
  },
}
